name: api-test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

    tags: ["*"]
    
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - uses: actions/checkout@v3
      - name: Install Newman
        run: npm install -g newman
