name: api-test
on:
  pull_request:
    branches:
      - main
      - dev
      - staging
      - authenciation_apis
  push:
    branches:
      - main
      - dev
      - staging
    tags: ["*"]
permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.47

          # Optional: working directory, useful for monorepos
          working-directory: core_service_api
          
          # Optional: golangci-lint command line arguments.
          args: --verbose --timeout 3m0s
