name: api-test
on:
  workflow_dispatch:
    inputs:
        tenent:
          description: 'Company Name'
          required: true
          default: 'sharpsell'
          
env:
  TESTRAIL_USERNAME: vignesh.babu@sharpsell.ai
  TESTRAIL_APIKEY: z3jAqqBzglccwqVrsYQd-5B1kE1BGaDVbSc.FsTpa
  TESTRAIL_DOMAIN: sharpsell.testrail.com
  TESTRAIL_PROJECTID: 1
  TESTRAIL_SUITEID: 1
    
jobs:
  newman:
    name: API Test Workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Newman
        run: npm install -g newman
      - name: Install Testrail Reporter
        run: npm install -g newman-reporter-testrail
      - name: Run newman
        run: newman run appuser.json -e environment.json -g globals.json --reporters cli,testrail
